<x-filament-panels::page>
    <div class="mx-auto max-w-2xl">
        <x-filament::section>
            <x-slot name="heading">
                Two-Factor Authentication (2FA)
            </x-slot>

            <x-slot name="description">
                Add an extra layer of security to your account by requiring a verification code during login.
            </x-slot>

            <div class="space-y-6">
                @if ($isEnabled)
                    <div class="flex items-center gap-4 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-400">
                        <div class="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-500/20">
                            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                        </div>
                        <div>
                            <h3 class="text-lg font-medium text-white">2FA is Enabled</h3>
                            <p class="text-sm text-gray-400">Your account is secured with two-factor authentication.</p>
                        </div>
                    </div>

                    <div class="mt-6 flex justify-end">
                        <x-filament::button wire:click="disable" color="danger">
                            Disable 2FA
                        </x-filament::button>
                    </div>
                @else
                    <div class="flex items-center gap-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-amber-400">
                        <div class="flex h-10 w-10 items-center justify-center rounded-full bg-amber-500/20">
                            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                            </svg>
                        </div>
                        <div>
                            <h3 class="text-lg font-medium text-white">2FA is Not Enabled</h3>
                            <p class="text-sm text-gray-400">We strongly recommend enabling two-factor authentication to secure your admin account.</p>
                        </div>
                    </div>

                    <div class="mt-6 space-y-6">
                        <div>
                            <h4 class="text-base font-semibold text-white">Step 1: Scan this QR Code</h4>
                            <p class="text-sm text-gray-400">Scan the QR code below using your authenticator app (Google Authenticator, Microsoft Authenticator, Authy, etc.).</p>
                            
                            <div class="mt-4 flex justify-center rounded-xl bg-white p-6 w-fit mx-auto shadow-inner">
                                {!! $qrCodeUri !!}
                            </div>
                            
                            <div class="mt-4 text-center">
                                <span class="text-xs text-gray-400">Or manually enter this code:</span>
                                <code class="block mt-1 text-sm font-bold bg-gray-800 border border-gray-700 rounded px-2 py-1 select-all text-violet-400 tracking-wider">{{ $secretKey }}</code>
                            </div>
                        </div>

                        <hr class="border-gray-800">

                        <div>
                            <h4 class="text-base font-semibold text-white">Step 2: Enter Verification Code</h4>
                            <p class="text-sm text-gray-400">Enter the 6-digit code generated by your app to verify the setup.</p>
                            
                            <form wire:submit="enable" class="mt-4 space-y-4">
                                <div class="max-w-xs mx-auto">
                                    <x-filament::input.wrapper :valid="!$errors->has('code')">
                                        <x-filament::input
                                            type="text"
                                            wire:model="code"
                                            required
                                            maxlength="6"
                                            placeholder="000000"
                                            class="text-center font-bold tracking-widest text-lg"
                                        />
                                    </x-filament::input.wrapper>
                                    @error('code')
                                        <p class="mt-2 text-sm text-rose-500 text-center">{{ $message }}</p>
                                    @enderror
                                </div>
                                
                                <div class="flex justify-center">
                                    <x-filament::button type="submit" color="primary">
                                        Verify & Enable 2FA
                                    </x-filament::button>
                                </div>
                            </form>
                        </div>
                    </div>
                @endif
            </div>
        </x-filament::section>
    </div>
</x-filament-panels::page>
